Repository nissl-lab/npoi, pull requests merged in 2023-08, with the labels that each got.

#1128 Fix removing hyperlinks
  ooxml/XSSF/UserModel/XSSFSheet.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFBugs.cs
Labels: xlsx

#1171 Fix XSSFSheet.RemoveHyperlink method.
  ooxml/XSSF/UserModel/XSSFSheet.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFBugs.cs
Labels: bug, file_error, xlsx

#1135 Support (FLOOR|CEILING).MATH & (VAR|STDEV).(P|S) functions
  main/NPOI.Core.csproj
  main/SS/Formula/Atp/AnalysisToolPak.cs
  main/SS/Formula/Functions/CeilingMath.cs
  main/SS/Formula/Functions/FloorCeilingMathBase.cs
  main/SS/Formula/Functions/FloorMath.cs
  main/SS/Formula/Functions/NumberListFuncBase.cs
  main/SS/Formula/Functions/StdevP.cs
  main/SS/Formula/Functions/StdevS.cs
  main/SS/Formula/Functions/ValueEvaluationHelper.cs
  main/SS/Formula/Functions/VarP.cs
  main/SS/Formula/Functions/VarS.cs
  main/SS/Util/DoublePrecisionHelper.cs
  test.runsettings
  testcases/main/Util/TestDoublePrecisionHelper.cs
  testcases/ooxml/SS/Formula/Functions/CompareNumericFuncEvalTestBase.cs
  testcases/ooxml/SS/Formula/Functions/TestFloorCeilingMath.cs
  testcases/ooxml/SS/Formula/Functions/TestStdevAndVarVariants.cs
  testcases/test-data/functions/FloorCeilingMath.xlsx
  testcases/test-data/functions/StDevAndVar.xlsx
Labels: xls, xlsx, formula
