Repository nissl-lab/npoi, pull requests merged in 2023-10, with the labels that each got.

#1181 Fix DefaultColumnWidth
  OpenXmlFormats/Spreadsheet/Sheet.cs
  main/HSSF/Model/InternalSheet.cs
  main/HSSF/Record/Aggregates/ColumnInfoRecordsAggregate.cs
  main/HSSF/UserModel/HSSFSheet.cs
  main/SS/UserModel/Sheet.cs
  ooxml/SS/Converter/ExcelToHtmlConverter.cs
  ooxml/SS/Converter/ExcelToHtmlUtils.cs
  ooxml/XSSF/Streaming/SXSSFSheet.cs
  ooxml/XSSF/UserModel/XSSFDialogsheet.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  openxml4Net/Util/XmlHelper.cs
  testcases/main/HSSF/UserModel/TestHSSFSheet.cs
  testcases/main/SS/UserModel/BaseTestBugzillaIssues.cs
  testcases/main/SS/UserModel/BaseTestSheetAutosizeColumn.cs
  testcases/ooxml/XSSF/Streaming/TestSXSSFSheetAutoSizeColumn.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFSheet.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFWorkbook.cs
Labels: bug, xls, xlsx

#1159 Remove reflections in `DDF.EscherRecord` and `HSSF.Record`
  main/DDF/DefaultEscherRecordFactory.cs
  main/HSSF/Record/CFHeader12Record.cs
  main/HSSF/Record/CFHeaderRecord.cs
  main/HSSF/Record/CFRule12Record.cs
  main/HSSF/Record/CFRuleRecord.cs
  main/HSSF/Record/Chart/LinkedDataRecord.cs
  main/HSSF/Record/Chart/StartBlockRecord.cs
  main/HSSF/Record/RecordFactory.cs
Labels: aot

#1162 Remove reflections in POI Logger
  main/Util/CustomPOILoggerFactory.cs
  main/Util/POILogFactory.cs
Labels: aot

#1161 Remove reflections in unused (or not working) classes
  main/HSSF/UserModel/OperationEvaluatorFactory.cs
  main/POIFS/NIO/FileBackedDataSource.cs
  main/SS/Formula/Eval/Forked/ForkedEvaluator.cs
  openxml4Net/Util/ZipSecureFile.cs
Labels: aot

#1137 Remove reflections: Misc and Summary
  OpenXmlFormats/OOXMLFactory.cs
  OpenXmlFormats/Wordprocessing/Table.cs
  main/HPSF/MutableSection.cs
  main/HSSF/EventUserModel/EventWorkbookBuilder.cs
  main/HSSF/Model/LinkTable.cs
  main/HSSF/Model/RowBlocksReader.cs
  main/HSSF/UserModel/HSSFWorkbook.cs
  main/SS/Formula/CellEvaluationFrame.cs
  main/SS/Formula/CollaboratingWorkbooksEnvironment.cs
  main/SS/Formula/EvaluationConditionalFormatRule.cs
  main/SS/Formula/FormulaParser.cs
  main/SS/Formula/OperationEvaluatorFactory.cs
  main/SS/Formula/PTG/AttrPtg.cs
  main/SS/Formula/PTG/OperandPtg.cs
  main/SS/Formula/PTG/Ptg.cs
  main/SS/Formula/PTG/UnknownPtg.cs
  main/SS/Util/AreaReference.cs
  main/SS/Util/CellRangeAddressList.cs
  main/SS/Util/CellRangeUtil.cs
  main/SS/Util/SSCellRange.cs
  main/Util/CollectionExtensions.cs
  main/Util/HexRead.cs
  main/Util/ObjectExtensions.cs
  ooxml/POIXMLDocument.cs
  ooxml/Util/CollectionExtensions.cs
  ooxml/Util/EnumConverter.cs
  ooxml/XSSF/UserModel/XSSFTable.cs
  ooxml/XSSF/Util/XmlEnumParser.cs
Labels: aot

#1178 Small speedup on autosizing column width
  main/SS/Util/SheetUtil.cs
Labels: performance

#1176 Workbook Evaluator bug fix on checking an IF without a third param
  main/SS/Formula/WorkbookEvaluator.cs
Labels: xls, xlsx, formula

#1157 Remove reflections in `POIXMLFactory.CreateDocumentPart`
  ooxml/Util/DocumentPartCreationHelper.cs
  ooxml/XSSF/UserModel/XSSFChart.cs
  ooxml/XSSF/UserModel/XSSFChartSheet.cs
  ooxml/XSSF/UserModel/XSSFFactory.cs
  ooxml/XSSF/UserModel/XSSFPivotCache.cs
  ooxml/XSSF/UserModel/XSSFPivotCacheDefinition.cs
  ooxml/XSSF/UserModel/XSSFPivotCacheRecords.cs
  ooxml/XSSF/UserModel/XSSFPivotTable.cs
  ooxml/XSSF/UserModel/XSSFVMLDrawing.cs
  ooxml/XWPF/Usermodel/XWPFFactory.cs
  ooxml/XWPF/Usermodel/XWPFPictureData.cs
Labels: aot
