Repository nissl-lab/npoi, pull requests merged in 2023-07, with the labels that each got.

#1120 Support replacing docx text within embedded tables
  ooxml/XWPF/Usermodel/XWPFDocument.cs
Labels: bug, docx

#1095 Reduce string allocations when writing documents
  OpenXmlFormats/CustomXmlSchemaProperties.cs
  OpenXmlFormats/Drawing/WordprocessingDrawing.cs
  OpenXmlFormats/Spreadsheet/Document/CalcChainDocument.cs
  OpenXmlFormats/Spreadsheet/Sheet.cs
  OpenXmlFormats/Spreadsheet/Sheet/CT_Cell.cs
  OpenXmlFormats/Spreadsheet/Sheet/CT_Row.cs
  OpenXmlFormats/StreamWriterExtensions.cs
  OpenXmlFormats/Vml/WordprocessingDrawing.cs
  OpenXmlFormats/Wordprocessing/BaseTypes.cs
  OpenXmlFormats/Wordprocessing/CustomXml.cs
  OpenXmlFormats/Wordprocessing/Document.cs
  OpenXmlFormats/Wordprocessing/FormField.cs
  OpenXmlFormats/Wordprocessing/Frame.cs
  OpenXmlFormats/Wordprocessing/HdrFtr.cs
  OpenXmlFormats/Wordprocessing/Markup.cs
  OpenXmlFormats/Wordprocessing/Numbering.cs
  OpenXmlFormats/Wordprocessing/PageSetup.cs
  OpenXmlFormats/Wordprocessing/Paragraph.cs
  OpenXmlFormats/Wordprocessing/Picture.cs
  OpenXmlFormats/Wordprocessing/RangePermission.cs
  OpenXmlFormats/Wordprocessing/Run.cs
  OpenXmlFormats/Wordprocessing/Sdt.cs
  OpenXmlFormats/Wordprocessing/Settings.cs
  OpenXmlFormats/Wordprocessing/Styles.cs
  OpenXmlFormats/Wordprocessing/Tab.cs
  OpenXmlFormats/Wordprocessing/Table.cs
  OpenXmlFormats/Wordprocessing/wml.cs
  openxml4Net/Util/XmlHelper.cs
Labels: performance, xlsx

#1119 Add DateOnlyCellValue and TimeOnlyCellValue
  main/HSSF/UserModel/HSSFCell.cs
  main/SS/Format/CellFormat.cs
  main/SS/UserModel/Cell.cs
  main/SS/UserModel/DataFormatter.cs
  ooxml/XSSF/Streaming/SXSSFCell.cs
  ooxml/XSSF/UserModel/XSSFCell.cs
  testcases/main/HSSF/UserModel/TestHSSFCell.cs
  testcases/main/HSSF/UserModel/TestHSSFDateUtil.cs
  testcases/main/SS/UserModel/BaseTestCell.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFWorkbook.cs
Labels: enhancement, sxssf, xls, xlsx
