Repository nissl-lab/npoi, pull requests merged in 2023-12, with the labels that each got.

#1235 fix: Do not save Style with index 0
  OpenXmlFormats/Spreadsheet/Sheet/CT_Cell.cs
Labels: bug, xlsx

#1238 Upgrade Microsoft.IO.RecyclableMemoryStream to version 3.0.0
  main/NPOI.Core.csproj
Labels: enhancement

#942 fix/Workseet-CopyTo-performance
  main/HSSF/UserModel/HSSFSheet.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  testcases/main/HSSF/UserModel/TestHSSFSheetCopy.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFSheetCopyTo.cs
Labels: enhancement, performance

#1197 feat freeform for shapes
  .editorconfig
  OpenXmlFormats/Drawing/ShapeGeometry.cs
  OpenXmlFormats/Drawing/SpreadsheetDrawing.cs
  OpenXmlFormats/Drawing/spreadsheetShape.cs
  main/SS/Util/SheetUtil.cs
  main/Util/Coordinate.cs
  ooxml/XSSF/UserModel/XSSFClientAnchor.cs
  ooxml/XSSF/UserModel/XSSFDrawing.cs
  ooxml/XSSF/UserModel/XSSFFreeform.cs
  ooxml/XSSF/UserModel/XSSFPrintSetup.cs
  ooxml/XSSF/UserModel/XSSFShapeGroup.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  solution/NPOI.Core.Test.sln
  testcases/ooxml/XSSF/UserModel/TestXSSFShape.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFSheet.cs
  testcases/test-data/spreadsheet/SetDefaultColumnWidth.xlsx
  testcases/test-data/spreadsheet/TestBuildFreeform.xlsx
Labels: drawing

#1213 Fix saving docx in compatibility mode
  OpenXmlFormats/Wordprocessing/Settings.cs
Labels: bug, docx
