Repository nissl-lab/npoi, pull requests merged in 2023-02, with the labels that each got.

#1006 Add docx comment support
  OpenXmlFormats/Wordprocessing/Document/CommentsDocument.cs
  OpenXmlFormats/Wordprocessing/Markup.cs
  OpenXmlFormats/Wordprocessing/Paragraph.cs
  OpenXmlFormats/Wordprocessing/Run.cs
  ooxml/NPOI.OOXML.csproj
  ooxml/XWPF/Usermodel/BodyType.cs
  ooxml/XWPF/Usermodel/XWPFComment.cs
  ooxml/XWPF/Usermodel/XWPFComments.cs
  ooxml/XWPF/Usermodel/XWPFDocument.cs
  ooxml/XWPF/Usermodel/XWPFRelation.cs
  ooxml/XWPF/Usermodel/XWPFRun.cs
  testcases/ooxml/XWPF/UserModel/TestXWPFComment.cs
  testcases/ooxml/XWPF/UserModel/TestXWPFComments.cs
  testcases/test-data/document/comment.docx
  testcases/test-data/document/testComment.docx
Labels: enhancement

#1014 fix POI Bug 60197 - setSheetOrder doesn't update names scope
  main/HSSF/UserModel/HSSFWorkbook.cs
  ooxml/XSSF/UserModel/XSSFWorkbook.cs
  testcases/main/SS/UserModel/BaseTestBugzillaIssues.cs
  testcases/ooxml/XSSF/Streaming/TestSXSSFBugs.cs
Labels: bug

#953 Stop MutableSection from setting null MutableProperty
  main/HPSF/MutableSection.cs
Labels: bug, xls

#1027 fix `Ambiguous project name` error while restoring NuGet packages.
  OpenXmlFormats/NPOI.OpenXmlFormats.csproj
  main/NPOI.Core.csproj
  main/NPOI.csproj
  ooxml/NPOI.OOXML.csproj
  openxml4Net/NPOI.OpenXml4Net.csproj
Labels: bug

#1034 Exception cleanup
  main/DDF/DefaultEscherRecordFactory.cs
  main/DDF/EscherTextboxRecord.cs
  main/DDF/UnknownEscherRecord.cs
  main/HPSF/MutableSection.cs
  main/HSSF/Extractor/EventBasedExcelExtractor.cs
  main/HSSF/Extractor/OldExcelExtractor.cs
  main/HSSF/Record/RecordFactory.cs
  main/HSSF/UserModel/OperationEvaluatorFactory.cs
  main/HSSF/Util/HSSFCellUtil.cs
  main/POIFS/Crypt/Standard/StandardDecryptor.cs
  main/POIFS/Crypt/Standard/StandardEncryptor.cs
  main/POIFS/FileSystem/DirectoryNode.cs
  main/POIFS/FileSystem/NPOIFSFileSystem.cs
  main/POIFS/Macros/VBAMacroReader.cs
  main/POIFS/Storage/HeaderBlock.cs
  main/POIFS/Storage/HeaderBlockWriter.cs
  main/POIFS/property/NPropertyTable.cs
  main/POIFS/property/PropertyTableBase.cs
  main/SS/Format/CellFormat.cs
  main/SS/Format/CellNumberStringMod.cs
  main/SS/Formula/Atp/Switch.cs
  main/SS/Formula/Atp/XLookupFunction.cs
  main/SS/Formula/Atp/XMatchFunction.cs
  main/SS/Formula/Eval/OperandResolver.cs
  main/SS/Formula/EvaluationConditionalFormatRule.cs
  main/SS/Formula/FormulaParser.cs
  main/SS/Formula/Function/FunctionMetadataReader.cs
  main/SS/Formula/Functions/Areas.cs
  main/SS/Formula/Functions/NumberValueFunction.cs
  main/SS/Formula/Functions/Sumproduct.cs
  main/SS/Formula/Functions/Text/Text.cs
  main/SS/Formula/WorkbookEvaluator.cs
  main/SS/Util/SheetUtil.cs
  main/Util/CRC32.cs
  main/Util/CodePageUtil.cs
  main/Util/SystemOutLogger.cs
  ooxml/POIFS/Crypt/Agile/AgileEncryptionHeader.cs
  ooxml/POIXMLDocumentPart.cs
  ooxml/SS/UserModel/WorkbookFactory.cs
  ooxml/XSSF/Streaming/SheetDataWriter.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  openxml4Net/OPC/OPCPackage.cs
  openxml4Net/OPC/PackagingUriHelper.cs
  openxml4Net/OPC/ZipPackage.cs
Labels: enhancement
