Repository nissl-lab/npoi, pull requests merged in 2024-11, with the labels that each got.

#1329 XSSFColumn class implementation
  OpenXmlFormats/Spreadsheet/Sheet/CT_Col.cs
  OpenXmlFormats/Spreadsheet/Sheet/CT_Cols.cs
  OpenXmlFormats/Spreadsheet/Sheet/CT_Row.cs
  OpenXmlFormats/Spreadsheet/Sheet/CT_SheetData.cs
  OpenXmlFormats/Spreadsheet/Sheet/CT_Worksheet.cs
  main/HSSF/UserModel/HSSFSheet.cs
  main/SS/Formula/FormulaShifter.cs
  main/SS/UserModel/CellCopyPolicy.cs
  main/SS/UserModel/Column.cs
  main/SS/UserModel/Helpers/RowShifter.cs
  main/SS/UserModel/Sheet.cs
  main/SS/Util/CellUtil.cs
  ooxml/XSSF/Streaming/SXSSFSheet.cs
  ooxml/XSSF/UserModel/Helpers/ColumnHelper.cs
  ooxml/XSSF/UserModel/Helpers/ColumnShifter.cs
  ooxml/XSSF/UserModel/Helpers/XSSFColumnShifter.cs
  ooxml/XSSF/UserModel/Helpers/XSSFRowColShifter.cs
  ooxml/XSSF/UserModel/XSSFCell.cs
  ooxml/XSSF/UserModel/XSSFColumn.cs
  ooxml/XSSF/UserModel/XSSFRow.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  testcases/main/HSSF/Extractor/TestOldExcelExtractor.cs
  testcases/main/SS/Formula/Atp/TestNetworkdaysFunction.cs
  testcases/main/SS/Formula/Functions/TestBesselJ.cs
  testcases/main/SS/Formula/Functions/TestComplex.cs
  testcases/main/SS/Formula/Functions/TestDec2Bin.cs
  testcases/main/SS/Formula/Functions/TestDec2Hex.cs
  testcases/main/SS/Formula/Functions/TestDelta.cs
  testcases/main/SS/Formula/Functions/TestDollarDe.cs
  testcases/main/SS/Formula/Functions/TestDollarFr.cs
  testcases/main/SS/Formula/Functions/TestFixed.cs
  testcases/main/SS/Formula/Functions/TestNormDist.cs
  testcases/main/SS/Formula/Functions/TestNormInv.cs
  testcases/main/SS/Formula/Functions/TestNormSDist.cs
  testcases/main/SS/Formula/Functions/TestNormSInv.cs
  testcases/main/SS/Formula/Functions/TestNumberValue.cs
  testcases/main/SS/Formula/Functions/TestNumericFunction.cs
  testcases/main/SS/Formula/Functions/TestQuotient.cs
  testcases/main/SS/Formula/Functions/TestStandardize.cs
  testcases/main/SS/Formula/Functions/TestTDist.cs
  testcases/main/SS/Formula/Functions/TestText.cs
  testcases/main/SS/UserModel/TestFractionFormat.cs
  testcases/main/Util/TestStringUtil.cs
  testcases/ooxml/XSSF/Streaming/SheetDataWriterTests.cs
  testcases/ooxml/XSSF/UserModel/Helpers/TestColumnHelper.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFColGrouping.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFColumn.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFSheet.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFSheetColumns.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFTextRun.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFWorkbook.cs
Labels: enhancement, xlsx

#1441 Fix Clone sheet when the sheet contains hyperlinks
  ooxml/XSSF/UserModel/XSSFWorkbook.cs
  testcases/ooxml/XSSF/UserModel/TestCloneSheet.cs
  testcases/test-data/spreadsheet/1370_clonesheet_withhyperlink.xlsx
Labels: bug, xlsx

#1434 Port POI patches
  OpenXmlFormats/Spreadsheet/Sheet.cs
  OpenXmlFormats/Spreadsheet/Sheet/CT_Worksheet.cs
  main/SS/Formula/FormulaParser.cs
  main/Util/StringUtil.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  testcases/main/SS/UserModel/BaseTestNamedRange.cs
  testcases/main/SS/UserModel/BaseTestSheet.cs
  testcases/ooxml/XSSF/SXSSFITestDataProvider.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFSheet.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFSheetShiftRows.cs
  testcases/test-data/spreadsheet/unicodeSheetName.xlsx
Labels: bug

#1446 Poi bug 60605: convert Workbook.SHEET_STATE_* to SheetVisibility enum
  main/HSSF/Model/InternalWorkbook.cs
  main/HSSF/UserModel/HSSFWorkbook.cs
  main/SS/UserModel/SheetVisibility.cs
  main/SS/UserModel/Workbook.cs
  main/SS/Util/WorkbookUtil.cs
  ooxml/XSSF/Streaming/SXSSFWorkbook.cs
  ooxml/XSSF/UserModel/XSSFWorkbook.cs
  testcases/main/HSSF/UserModel/TestBugs.cs
  testcases/main/SS/UserModel/BaseTestSheetHiding.cs
Labels: bug, xls, xlsx

#1447 poi bug 60031: DataFormatter parses months incorrectly when put at the end of date segment.
  main/SS/UserModel/DataFormatter.cs
  testcases/main/HSSF/UserModel/TestHSSFSheet.cs
  testcases/main/POITestCase.cs
  testcases/main/SS/UserModel/BaseTestSheet.cs
  testcases/main/SS/UserModel/TestDataFormatter.cs
Labels: bug, poi
