Repository nissl-lab/npoi, pull requests merged in 2024-07, with the labels that each got.

#1373 Use Directory.Build.props as single source of version information
  Directory.Build.props
  OpenXmlFormats/Properties/AssemblyInfo.cs
  build/Build.GitHubAction.cs
  build/Build.cs
  main/Properties/AssemblyInfo.cs
  ooxml/Properties/AssemblyInfo.cs
  openxml4Net/Properties/AssemblyInfo.cs
Labels: cicd

#1378 Fix RepositoryUrl in Directory.Build.props
  Directory.Build.props
Labels: cicd

#1377 UnhandledDataStructure should sanity check before allocating, not after
  scratchpad/HWPF/Model/UnhandledDataStructure.cs
Labels: hwpf

#1374 fixing a NPE in GetSymbolFont
  scratchpad/HWPF/UserModel/CharacterRun.cs
Labels: bug, hwpf

#1391 FindAndReplaceText will now also work for tables within a documents h…
  ooxml/XWPF/Usermodel/XWPFDocument.cs
Labels: enhancement, docx
