Repository nissl-lab/npoi, pull requests merged in 2024-10, with the labels that each got.

#1429 Fix checking if cell style is set
  OpenXmlFormats/Spreadsheet/Sheet/CT_Cell.cs
Labels: bug, xlsx

#1430 Update version of System.Security.Cryptography
  Directory.Packages.props
Labels: cicd

#1431 fix unit test failures
  OpenXmlFormats/Wordprocessing/wml.cs
  testcases/ooxml/SS/Converter/TestExcelToHtmlConverterSuite.cs
Labels: bug

#1379 fixing an error in adobe meta
  scratchpad/HWPF/Converter/FoDocumentFacade.cs
Labels: bug, hwpf

#1385 fixed SXSSFWorkbook can not clear temp files when it called Dispose() on the IWorkbook interface.
  ooxml/XSSF/Streaming/SXSSFWorkbook.cs
Labels: bug, sxssf

#1435 Reduce array allocations by usage MemoryStream.GetBuffer() instead of ToArray()
  main/DDF/EscherBSERecord.cs
  main/DDF/EscherBlipWMFRecord.cs
  main/HPSF/MutableSection.cs
  main/HSSF/Record/Crypto/Biff8EncryptionKey.cs
  main/POIFS/Storage/HeaderBlockWriter.cs
  main/Util/HexDump.cs
  ooxml/POIFS/Crypt/Agile/AgileEncryptor.cs
  openxml4Net/OPC/OPCPackage.cs
Labels: performance
