Repository nissl-lab/npoi, pull requests merged in 2024-08, with the labels that each got.

#1400 Remove System.Configuration.ConfigurationManager as NuGet dependency
  main/NPOI.Core.csproj
  main/Util/POILogFactory.cs
  main/Util/SystemOutLogger.cs
  testcases/main/NPOI.TestCases.Core.csproj
Labels: cicd

#1390 Convert to use Central Package Management
  Directory.Build.props
  Directory.Packages.props
  benchmarks/NPOI.Benchmarks/NPOI.Benchmarks.csproj
  build/_build.csproj
  main/NPOI.Core.csproj
  ooxml/NPOI.OOXML.Core.csproj
  solution/NPOI.Core.Test.sln
  testcases/main/NPOI.TestCases.Core.csproj
  testcases/ooxml/NPOI.OOXML.TestCases.Core.csproj
  testcases/openxml4net/NPOI.OOXML4Net.TestCases.Core.csproj
Labels: cicd

#1402 Upgrade SixLabors.ImageSharp to version 2.1.9
  Directory.Packages.props
Labels: security

#1408 fix: Inconsistent new lines in worksheets
  ooxml/XSSF/Streaming/SheetDataWriter.cs
  testcases/ooxml/XSSF/Streaming/SheetDataWriterTests.cs
Labels: bug, sxssf

#1403 maxRows is usefull for AutoSizeColumn and GetColumnWidth
  main/HSSF/UserModel/HSSFSheet.cs
  main/SS/Util/SheetUtil.cs
Labels: enhancement, xls
