Repository nissl-lab/npoi, pull requests merged in 2025-03, with the labels that each got.

#1492 [POI 66093 & POI 62373] Support FREQUENCY function and subfunctions to SUBTOTAL function
  main/SS/Formula/Atp/XLookupFunction.cs
  main/SS/Formula/Eval/AreaEval.cs
  main/SS/Formula/Eval/AreaEvalBase.cs
  main/SS/Formula/Eval/FunctionEval.cs
  main/SS/Formula/Functions/AggregateFunction.cs
  main/SS/Formula/Functions/Count.cs
  main/SS/Formula/Functions/Counta.cs
  main/SS/Formula/Functions/Frequency.cs
  main/SS/Formula/Functions/StatsLib.cs
  main/SS/Formula/Functions/Subtotal.cs
  main/SS/Formula/TwoDEval.cs
  testcases/main/SS/Formula/Functions/TestFrequency.cs
  testcases/main/SS/Formula/Functions/TestSubtotal.cs
Labels: bug, poi

#1497 Fix int overflowing in ExcelGeneralNumberFormat
  main/SS/UserModel/ExcelGeneralNumberFormat.cs
Labels: bug, formula

#1470 Inconsistent formatting when reading multiple XLS files concurrently (#1469)
  benchmarks/NPOI.Benchmarks/DataFormatReadBenchmark.cs
  main/HSSF/UserModel/HSSFCellStyle.cs
  testcases/main/HSSF/UserModel/TestCellStyle.cs
Labels: performance, xls

#1500 Use TryGetValue instead of ContainsKey and indexing
  main/DDF/DefaultEscherRecordFactory.cs
  main/HSSF/Model/InternalWorkbook.cs
  main/HSSF/Record/Aggregates/SharedValueManager.cs
  main/HSSF/Record/Drawing/OfficeArtFOPT.cs
  main/HSSF/Record/EscherAggregate.cs
  main/HSSF/Record/RecordFactory.cs
  main/HSSF/UserModel/HSSFRow.cs
  main/HSSF/UserModel/HSSFSheet.cs
  main/HSSF/UserModel/HSSFWorkbook.cs
  main/HSSF/Util/HSSFCellUtil.cs
  main/HSSF/Util/HSSFColor.cs
  main/SS/Format/CellFormat.cs
  main/SS/Format/CellFormatCondition.cs
  main/SS/Format/CellFormatPart.cs
  main/SS/Formula/Atp/AnalysisToolPak.cs
  main/SS/Formula/Atp/WorkdayCalculator.cs
  main/SS/Formula/CollaboratingWorkbooksEnvironment.cs
  main/SS/Formula/Eval/ErrorEval.cs
  main/SS/Formula/Eval/Forked/ForkedEvaluationSheet.cs
  main/SS/Formula/Eval/Forked/ForkedEvaluationWorkbook.cs
  main/SS/Formula/EvaluationConditionalFormatRule.cs
  main/SS/Formula/Functions/FactDouble.cs
  main/SS/Formula/Functions/LookupUtils.cs
  main/SS/Formula/WorkbookEvaluator.cs
  main/SS/HtmlDocumentFacade.cs
  main/SS/UserModel/Drawing/OfficeArtProperties.cs
  main/SS/UserModel/ExtendedColor.cs
  main/SS/UserModel/FormulaError.cs
  main/SS/UserModel/IndexedColors.cs
  main/SS/Util/DateFormatConverter.cs
  main/SS/Util/PropertyTemplate.cs
  main/Util/IntMapper.cs
  main/Util/ObjectExtensions.cs
  ooxml/POIXMLDocumentPart.cs
  ooxml/SS/Converter/ExcelToHtmlConverter.cs
  ooxml/XSSF/Extractor/XSSFExportToXml.cs
  ooxml/XSSF/Model/CommentsTable.cs
  ooxml/XSSF/Model/SharedStringsTable.cs
  ooxml/XSSF/Model/StylesTable.cs
  ooxml/XSSF/Streaming/AutoSizeColumnTracker.cs
  ooxml/XSSF/Streaming/SXSSFRow.cs
  ooxml/XSSF/Streaming/SXSSFSheet.cs
  ooxml/XSSF/Streaming/SXSSFWorkbook.cs
  ooxml/XSSF/UserModel/XSSFConditionalFormattingRule.cs
  ooxml/XSSF/UserModel/XSSFDataValidationHelper.cs
  ooxml/XSSF/UserModel/XSSFEvaluationSheet.cs
  ooxml/XSSF/UserModel/XSSFRelation.cs
  ooxml/XSSF/UserModel/XSSFRow.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  ooxml/XSSF/UserModel/XSSFTable.cs
  ooxml/XSSF/UserModel/XSSFWorkbook.cs
  ooxml/XSSF/Util/XmlEnumParser.cs
  ooxml/XWPF/Usermodel/XWPFDocument.cs
  ooxml/XWPF/Usermodel/XWPFRelation.cs
  openxml4Net/OPC/Internal/ContentTypeManager.cs
  openxml4Net/OPC/OPCPackage.cs
  openxml4Net/OPC/PackageRelationshipCollection.cs
  openxml4Net/OPC/ZipPackage.cs
Labels: enhancement, performance

#1505 Fixes #1503.
  Directory.Packages.props
Labels: cicd, security

#1473 Fixes #1472. Optimize CT_Row.Copy to reduce row cloning time under 1ms
  OpenXmlFormats/Wordprocessing/Table.cs
  ooxml/XWPF/Usermodel/XWPFTableRow.cs
Labels: bug, docx, performance

#1460 Implement GetCells interface for ISheet
  main/HSSF/UserModel/HSSFSheet.cs
  main/HSSF/Util/RangeAddress.cs
  main/NPOI.Core.csproj
  main/SS/UserModel/Sheet.cs
  main/SS/Util/CellRangeAddressList.cs
  main/SS/Util/SSCellRange.cs
  ooxml/XSSF/Streaming/SXSSFSheet.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  testcases/main/SS/UserModel/BaseTestSheet.cs
Labels: enhancement, api

#1479 Refactor some hpsf classes, deprecate Mutable* property classes
  main/HPSF/ClassID.cs
  main/HPSF/CustomProperties.cs
  main/HPSF/CustomProperty.cs
  main/HPSF/DocumentSummaryInformation.cs
  main/HPSF/Extractor/HPSFPropertiesExtractor.cs
  main/HPSF/MutableProperty.cs
  main/HPSF/MutablePropertySet.cs
  main/HPSF/MutableSection.cs
  main/HPSF/NoFormatIDException.cs
  main/HPSF/Property.cs
  main/HPSF/PropertySet.cs
  main/HPSF/PropertySetFactory.cs
  main/HPSF/Section.cs
  main/HPSF/SpecialPropertySet.cs
  main/HPSF/SummaryInformation.cs
  main/HPSF/TypeWriter.cs
  main/HPSF/Util.cs
  main/HPSF/VariantSupport.cs
  main/HPSF/Wellknown/PropertyIDMap.cs
  main/HPSF/Wellknown/SectionIDMap.cs
  main/HSSF/UserModel/HSSFWorkbook.cs
  main/POIFS/FileSystem/DirectoryEntry.cs
  main/POIFS/FileSystem/DirectoryNode.cs
  main/POIFS/FileSystem/FilteringDirectoryNode.cs
  main/POIFS/property/Property.cs
  main/Util/CodePageUtil.cs
  main/Util/Collections/BidirectionalDictionary/BidirectionalDictionary.cs
  main/Util/Collections/BidirectionalDictionary/DictionaryDebugView.cs
  main/Util/Collections/BidirectionalDictionary/IBidirectionalDictionary.cs
  main/Util/Collections/BidirectionalDictionary/IReadOnlyBidirectionalDictionary.cs
  main/Util/Collections/BidirectionalDictionary/LICENSE.md
  main/Util/Collections/BidirectionalDictionary/README-BidirectionalDictionary.md
  main/Util/Collections/BidirectionalDictionary/README.md
  main/Util/Collections/BidirectionalDictionary/ReadOnlyBidirectionalDictionary.cs
  main/Util/IOUtils.cs
  ooxml/XSSF/UserModel/XSSFChart.cs
  testcases/main/HPSF/Basic/TestBasic.cs
  testcases/main/HPSF/Basic/TestClassID.cs
  testcases/main/HPSF/Basic/TestEmptyProperties.cs
  testcases/main/HPSF/Basic/TestMetaDataIPI.cs
  testcases/main/HPSF/Basic/TestReadAllFiles.cs
  testcases/main/HPSF/Basic/TestWrite.cs
  testcases/main/HPSF/Basic/TestWriteWellKnown.cs
  testcases/main/HPSF/Basic/Util.cs
  testcases/main/HSSF/UserModel/TestHSSFWorkbook.cs
  testcases/main/HSSF/UserModel/TestOLE2Embeding.cs
  testcases/main/Util/TestClassID.cs
Labels: enhancement, poi

#1513 Reduce warning output during build and treat new warnings as errors
  Directory.Build.props
  benchmarks/NPOI.Benchmarks/NPOI.Benchmarks.csproj
  main/HPSF/Section.cs
  testcases/Directory.Build.props
Labels: cicd

#1515 Update build version to 2.7.3
  Directory.Build.props
Labels: cicd

#1518 Fix Unit Test Failures on Windows build server
  testcases/main/POIFS/FileSystem/TestOffice2007XMLException.cs
  testcases/main/SS/UserModel/BaseTestWorkbook.cs
  testcases/ooxml/XSSF/Streaming/TestSXSSFCell.cs
  testcases/ooxml/XSSF/Streaming/TestSXSSFWorkbook.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFColumn.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFSheetColumns.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFWorkbook.cs
Labels: cicd

#1523 Enable recommended NET analyzers and suppress errors
  Directory.Build.props
  OpenXmlFormats/Drawing/SpreadsheetPicture.cs
  ooxml/XSSF/UserModel/XSSFTable.cs
  ooxml/XSSF/UserModel/XSSFWorkbook.cs
Labels: cicd

#1527 Remove prefixes from cref tags
  main/DDF/EscherBSERecord.cs
  main/DDF/EscherBlipRecord.cs
  main/DDF/EscherBlipWMFRecord.cs
  main/DDF/EscherChildAnchorRecord.cs
  main/DDF/EscherClientAnchorRecord.cs
  main/DDF/EscherComplexProperty.cs
  main/DDF/EscherContainerRecord.cs
  main/DDF/EscherDgRecord.cs
  main/DDF/EscherDggRecord.cs
  main/DDF/EscherMetafileBlip.cs
  main/DDF/EscherPictBlip.cs
  main/DDF/EscherRecord.cs
  main/DDF/EscherSimpleProperty.cs
  main/DDF/EscherSpRecord.cs
  main/DDF/EscherSpgrRecord.cs
  main/DDF/EscherSplitMenuColorsRecord.cs
  main/DDF/EscherTextboxRecord.cs
  main/DDF/UnknownEscherRecord.cs
  main/HPSF/ClassID.cs
  main/HSSF/Record/Aggregates/FormulaRecordAggregate.cs
  main/HSSF/Record/FooterRecord.cs
  main/HSSF/UserModel/HSSFCellStyle.cs
  main/HSSF/UserModel/HSSFConditionalFormatting.cs
  main/HSSF/UserModel/HSSFFont.cs
  main/HSSF/UserModel/HSSFName.cs
  main/HSSF/UserModel/HSSFRichTextString.cs
  main/HSSF/UserModel/HSSFRow.cs
  main/POIFS/FileSystem/DocumentDescriptor.cs
  main/POIFS/FileSystem/POIFSDocumentPath.cs
  main/POIFS/FileSystem/POIFSDocumentReader.cs
  main/POIFS/FileSystem/POIFSDocumentWriter.cs
  main/POIFS/NIO/ByteArrayBackedDataSource.cs
  main/SS/Formula/Constant/ErrorConstant.cs
  main/Util/ByteField.cs
  main/Util/Collections/HashSet.cs
  main/Util/DelayableLittleEndianOutput.cs
  main/Util/IntegerField.cs
  main/Util/LittleEndian.cs
  main/Util/LittleEndianByteArrayInputStream.cs
  main/Util/LittleEndianByteArrayOutputStream.cs
  main/Util/LittleEndianInputStream.cs
  main/Util/LittleEndianOutputStream.cs
  main/Util/LongField.cs
  main/Util/PushbackInputStream.cs
  main/Util/PushbackStream.cs
  main/Util/ShortField.cs
  main/Util/ULongField.cs
Labels: cicd

#1528 Fix analyzer reported issues related to string usage
  Directory.Build.props
  OpenXmlFormats/NPOI.OpenXmlFormats.Core.csproj
  OpenXmlFormats/Spreadsheet/SharedString/CT_Rst.cs
  main/HSSF/Extractor/EventBasedExcelExtractor.cs
  main/HSSF/UserModel/DVConstraint.cs
  main/HSSF/UserModel/HSSFName.cs
  main/HSSF/UserModel/HSSFWorkbook.cs
  main/HSSF/UserModel/HeaderFooter.cs
  main/NPOI.Core.csproj
  main/Polyfills.cs
  main/SS/Format/CellFormat.cs
  main/SS/Format/CellFormatPart.cs
  main/SS/Format/CellGeneralFormatter.cs
  main/SS/Format/CellNumberFormatter.cs
  main/SS/Format/CellTextFormatter.cs
  main/SS/Formula/EvaluationConditionalFormatRule.cs
  main/SS/Formula/Functions/Bin2Dec.cs
  main/SS/Formula/Functions/DStarRunner.cs
  main/SS/Formula/Functions/DateValue.cs
  main/SS/Formula/Functions/NumberValueFunction.cs
  main/SS/UserModel/DataFormatter.cs
  main/SS/UserModel/ExcelStyleDateFormatter.cs
  main/SS/Util/AreaReference.cs
  main/SS/Util/CellRangeAddress.cs
  main/SS/Util/DateFormatConverter.cs
  main/SS/Util/Format.cs
  main/SS/Util/SheetUtil.cs
  main/Util/Collections/Properties.cs
  main/Util/Collections/StringTokenizer.cs
  main/Util/StringUtil.cs
  ooxml/NPOI.OOXML.Core.csproj
  ooxml/POIXMLDocumentPart.cs
  ooxml/POIXMLRelation.cs
  ooxml/SS/Converter/ExcelToHtmlConverter.cs
  ooxml/XSSF/Extractor/XSSFExportToXml.cs
  ooxml/XSSF/UserModel/BaseXSSFEvaluationWorkbook.cs
  ooxml/XSSF/UserModel/XSSFComment.cs
  ooxml/XSSF/UserModel/XSSFName.cs
  ooxml/XSSF/UserModel/XSSFRichTextString.cs
  ooxml/XSSF/UserModel/XSSFTable.cs
  ooxml/XSSF/UserModel/XSSFWorkbook.cs
  ooxml/XWPF/Usermodel/XWPFRun.cs
  ooxml/XWPF/Usermodel/XWPFSharedRun.cs
  openxml4Net/NPOI.OpenXml4Net.Core.csproj
  openxml4Net/OPC/ContentTypes.cs
  openxml4Net/OPC/Internal/PackagePropertiesPart.cs
  openxml4Net/OPC/OPCPackage.cs
  openxml4Net/OPC/PackagePart.cs
  openxml4Net/OPC/PackagePartName.cs
  openxml4Net/OPC/PackageRelationship.cs
  openxml4Net/OPC/PackagingUriHelper.cs
Labels: cicd

#1526 Fix dictionary usage related analyzer problems
  Directory.Build.props
  main/HPSF/Section.cs
  main/HSSF/Record/RecordFactory.cs
  main/POIFS/FileSystem/EntryUtils.cs
  main/POIFS/FileSystem/FilteringDirectoryNode.cs
  ooxml/POIXMLDocumentPart.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  ooxml/XSSF/UserModel/XSSFWorkbook.cs
  openxml4Net/OPC/Internal/ContentTypeManager.cs
Labels: cicd
