Repository nissl-lab/npoi, pull requests merged in 2025-04, with the labels that each got.

#1520 Some patches from poi 3.17
  main/SS/UserModel/BuiltinFormats.cs
  main/SS/UserModel/DataFormatter.cs
  ooxml/XSSF/Streaming/SXSSFWorkbook.cs
  testcases/main/HPSF/Extractor/TestHPSFPropertiesExtractor.cs
  testcases/main/HSSF/EventUserModel/TestFormatTrackingHSSFListener.cs
  testcases/main/HSSF/Extractor/TestExcelExtractor.cs
  testcases/main/HSSF/UserModel/TestBugs.cs
  testcases/main/POIFS/FileSystem/TestNPOIFSFileSystem.cs
  testcases/main/SS/UserModel/BaseTestWorkbook.cs
  testcases/main/SS/UserModel/TestDataFormatter.cs
  testcases/ooxml/TestXMLPropertiesTextExtractor.cs
  testcases/ooxml/XWPF/Extractor/TestXWPFWordExtractor.cs
  testcases/ooxml/XWPF/UserModel/TestXWPFSDT.cs
  testcases/ooxml/XWPF/UserModel/TestXWPFSmartTag.cs
  testcases/test-data/hsmf/lots-of-recipients.msg
Labels: bug, poi

#1541 Fix analyzer reported issues
  Directory.Build.props
  main/HSSF/Record/EscherAggregate.cs
  main/HSSF/UserModel/HSSFWorkbook.cs
  main/Polyfills.cs
  main/SS/Format/CellFormatPart.cs
  main/SS/Formula/Atp/AnalysisToolPak.cs
  main/SS/Formula/Eval/Forked/ForkedEvaluationSheet.cs
  main/SS/Formula/Eval/Forked/ForkedEvaluationWorkbook.cs
  main/SS/UserModel/DataFormatter.cs
  main/SS/Util/CellRangeAddressList.cs
  main/SS/Util/Format.cs
  main/SS/Util/SSCellRange.cs
  main/Util/IntMapper.cs
  openxml4Net/OPC/PackageRelationshipCollection.cs
Labels: performance

#1524 Fix XWPFDocument FindAndReplaceTextInParagraph
  ooxml/XWPF/Usermodel/XWPFDocument.cs
  testcases/ooxml/XWPF/UserModel/TestXWPFDocument.cs
  testcases/test-data/document/WordFindAndReplaceTextInParagraph.docx
Labels: bug, docx

#1519 Account for image resolution units other than pixels per inch
  main/SS/Util/ImageUtils.cs
Labels: drawing

#1543 Fix pattern formatting - return correct field for pattern fill foreground
  ooxml/XSSF/UserModel/XSSFPatternFormatting.cs
Labels: bug, xlsx

#1540 Some patches from poi
  OpenXmlFormats/Spreadsheet/Styles/CT_TableStyles.cs
  main/HSSF/UserModel/HSSFConditionalFormattingRule.cs
  main/SS/Formula/ConditionalFormattingEvaluator.cs
  main/SS/Formula/Functions/Irr.cs
  main/SS/Formula/Functions/LookupUtils.cs
  main/SS/Formula/Functions/Match.cs
  main/SS/UserModel/ConditionalFormattingRule.cs
  main/SS/UserModel/DataFormatter.cs
  main/SS/UserModel/DateUtil.cs
  main/SS/UserModel/DifferentialStyleProvider.cs
  main/SS/UserModel/Table.cs
  main/SS/UserModel/TableStyle.cs
  main/SS/UserModel/TableStyleInfo.cs
  main/SS/UserModel/TableStyleType.cs
  main/SS/Util/CellRangeAddress.cs
  main/SS/Util/CellReference.cs
  ooxml/SS/Converter/ExcelToHtmlConverter.cs
  ooxml/XSSF/Model/StylesTable.cs
  ooxml/XSSF/UserModel/XSSFBuiltinTableStyle.cs
  ooxml/XSSF/UserModel/XSSFConditionalFormattingRule.cs
  ooxml/XSSF/UserModel/XSSFDxfStyleProvider.cs
  ooxml/XSSF/UserModel/XSSFFont.cs
  ooxml/XSSF/UserModel/XSSFTableStyle.cs
  testcases/main/SS/Formula/Functions/TestMathX.cs
  testcases/main/SS/Formula/Functions/TestRoundFuncs.cs
  testcases/ooxml/XSSF/UserModel/TestTableStyles.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFDataFormat.cs
  testcases/test-data/spreadsheet/61060-conditional-number-formatting.xlsx
  testcases/test-data/spreadsheet/tableStyle.xlsx
Labels: bug, poi

#1535 Add InsertNewHyperlinkRun method, and fix InsertNewRun and RemoveRun methods
  ooxml/XWPF/Usermodel/XWPFParagraph.cs
  testcases/ooxml/XWPF/UserModel/TestXWPFParagraph.cs
Labels: enhancement, docx
