Repository nissl-lab/npoi, pull requests merged in 2025-06, with the labels that each got.

#1574 Implement ICellStyle.ReadingOrder
  main/HSSF/UserModel/HSSFCellStyle.cs
  main/SS/UserModel/CellStyle.cs
  main/SS/UserModel/ReadingOrder.cs
  ooxml/XSSF/UserModel/XSSFCellStyle.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFCellStyle.cs
Labels: enhancement, xlsx

#1572 Remove System.Security.Cryptography.Pkcs
  Directory.Packages.props
  ooxml/NPOI.OOXML.Core.csproj
Labels: enhancement, cicd

#1577 fix #1369
  OpenXmlFormats/Spreadsheet/Sheet.cs
  openxml4Net/Util/XmlHelper.cs
Labels: bug, file_error, xlsx

#1578 Fix CT_Point2D xml node prefix issue
  OpenXmlFormats/Drawing/BaseTypes.cs
  OpenXmlFormats/Drawing/SpreadsheetDrawing.cs
  OpenXmlFormats/Drawing/WordprocessingDrawing.cs
Labels: bug, file_error, docx

#1579 bug-65915 add test for 'OR' function
  main/SS/Formula/Atp/XLookupFunction.cs
  main/SS/Formula/Eval/RelationalOperationEval/RelationalOperationEval.cs
  main/SS/Formula/Eval/TwoOperandNumeric/TwoOperandNumericOperation.cs
  main/SS/Formula/Functions/ArrayFunction.cs
  main/SS/Formula/Functions/Boolean/BooleanFunction.cs
  main/SS/Formula/OperationEvaluatorFactory.cs
  main/SS/Formula/UserDefinedFunction.cs
  testcases/main/SS/Formula/Functions/TestOrFunction.cs
Labels: bug, formula, poi

#1580 Some patches from poi 3.17
  main/HSSF/Record/DimensionsRecord.cs
  main/HSSF/Record/FormatRecord.cs
  main/SS/Formula/Functions/Hlookup.cs
  main/SS/Formula/Functions/Lookup.cs
  main/SS/Formula/Functions/LookupUtils.cs
  main/SS/Formula/Functions/Vlookup.cs
  main/Util/IOUtils.cs
  testcases/main/HSSF/Extractor/TestExcelExtractor.cs
  testcases/main/HSSF/UserModel/TestHSSFCell.cs
  testcases/main/SS/Formula/Eval/TestFormulaBugs.cs
  testcases/ooxml/XSSF/Streaming/TestSXSSFBugs.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFBugs.cs
  testcases/ooxml/XSSF/XSSFTestDataSamples.cs
  testcases/test-data/spreadsheet/61045_govdocs1_626534.xls
Labels: bug, poi

#1584 Patches from poi 3.17
  OpenXmlFormats/Drawing/GraphicalObject.cs
  OpenXmlFormats/Spreadsheet/Styles/CT_Dxfs.cs
  main/SS/UserModel/ClientAnchor.cs
  main/Util/Units.cs
  ooxml/POIXMLDocument.cs
  ooxml/POIXMLDocumentPart.cs
  ooxml/XSSF/Streaming/SXSSFPicture.cs
  ooxml/XSSF/UserModel/Charts/XSSFCategoryAxis.cs
  ooxml/XSSF/UserModel/Charts/XSSFChartAxis.cs
  ooxml/XSSF/UserModel/Charts/XSSFDateAxis.cs
  ooxml/XSSF/UserModel/Charts/XSSFValueAxis.cs
  ooxml/XSSF/UserModel/XSSFClientAnchor.cs
  ooxml/XSSF/UserModel/XSSFDrawing.cs
  ooxml/XSSF/UserModel/XSSFGraphicFrame.cs
  ooxml/XSSF/UserModel/XSSFShape.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  ooxml/XSSF/UserModel/XSSFTableStyle.cs
  testcases/main/SS/UserModel/TestDataFormatter.cs
  testcases/ooxml/TestDetectAsOOXML.cs
  testcases/ooxml/XSSF/Model/TestStylesTable.cs
  testcases/test-data/spreadsheet/style-alternate-content.xlsx
Labels: bug, poi

#1589 Patches from poi 3.17
  main/SS/Format/CellDateFormatter.cs
  main/SS/Format/CellFormat.cs
  main/SS/Format/CellFormatPart.cs
  main/SS/Format/CellFormatType.cs
  main/SS/Format/CellFormatter.cs
  main/SS/Format/CellGeneralFormatter.cs
  main/SS/Format/CellNumberFormatter.cs
  main/SS/Formula/Functions/Mirr.cs
  main/SS/Formula/Functions/MultiOperandNumericFunction.cs
  main/SS/Formula/PTG/AbstractFunctionPtg.cs
  main/SS/UserModel/DataFormatter.cs
  main/SS/Util/Format.cs
  main/Util/Number.cs
  ooxml/XSSF/Streaming/SheetDataWriter.cs
  testcases/main/SS/Formula/Functions/TestMultiOperandNumericFunction.cs
  testcases/main/SS/Formula/PTG/TestAbstractFunctionPtg.cs
  testcases/main/SS/UserModel/TestDataFormatter.cs
  testcases/ooxml/XSSF/Streaming/TestSheetDataWriter.cs
  testcases/ooxml/XSSF/UserModel/TestCloneSheet.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFCell.cs
Labels: bug, poi

#1591 Update Version to 2.7.4
  Directory.Build.props
  Read Me.txt
  build/README.md
Labels: cicd
