Repository nissl-lab/npoi, pull requests merged in 2025-05, with the labels that each got.

#1552 Some patches from poi v3.17
  main/SS/Util/CellReference.cs
  ooxml/XSSF/Streaming/SXSSFSheet.cs
  ooxml/XSSF/UserModel/XSSFName.cs
  testcases/main/HSSF/UserModel/TestEscherGraphics.cs
  testcases/main/SS/Util/TestCellReference.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFName.cs
  testcases/test-data/spreadsheet/Helvetica.ttf
Labels: bug, poi

#1553 Patches from poi 3.17
  OpenXmlFormats/Spreadsheet/Styles/CT_Border.cs
  OpenXmlFormats/Spreadsheet/Styles/CT_BorderPr.cs
  OpenXmlFormats/Spreadsheet/Styles/CT_Colors.cs
  main/HSSF/UserModel/HSSFBorderFormatting.cs
  main/HSSF/UserModel/HSSFExtendedColor.cs
  main/SS/Formula/Eval/RefListEval.cs
  main/SS/Formula/Functions/Rank.cs
  main/SS/Formula/PTG/NamePtg.cs
  main/SS/Formula/WorkbookEvaluator.cs
  main/SS/UserModel/BorderFormatting.cs
  main/SS/UserModel/ExtendedColor.cs
  main/SS/UserModel/IndexedColors.cs
  main/SS/UserModel/Table.cs
  main/SS/UserModel/TableStyleType.cs
  main/SS/Util/CellRangeAddressBase.cs
  ooxml/XSSF/Model/StylesTable.cs
  ooxml/XSSF/Model/ThemesTable.cs
  ooxml/XSSF/UserModel/CustomIndexedColorMap.cs
  ooxml/XSSF/UserModel/DefaultIndexedColorMap.cs
  ooxml/XSSF/UserModel/Extensions/XSSFCellBorder.cs
  ooxml/XSSF/UserModel/Extensions/XSSFCellFill.cs
  ooxml/XSSF/UserModel/XSSFBorderFormatting.cs
  ooxml/XSSF/UserModel/XSSFBuiltinTableStyle.cs
  ooxml/XSSF/UserModel/XSSFCellStyle.cs
  ooxml/XSSF/UserModel/XSSFColor.cs
  ooxml/XSSF/UserModel/XSSFColorScaleFormatting.cs
  ooxml/XSSF/UserModel/XSSFConditionalFormattingRule.cs
  ooxml/XSSF/UserModel/XSSFCreationHelper.cs
  ooxml/XSSF/UserModel/XSSFDataBarFormatting.cs
  ooxml/XSSF/UserModel/XSSFDxfStyleProvider.cs
  ooxml/XSSF/UserModel/XSSFFont.cs
  ooxml/XSSF/UserModel/XSSFFontFormatting.cs
  ooxml/XSSF/UserModel/XSSFPatternFormatting.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  ooxml/XSSF/UserModel/XSSFTable.cs
  testcases/main/SS/Formula/TestWorkbookEvaluator.cs
  testcases/main/SS/UserModel/TestIndexedColors.cs
  testcases/ooxml/XSSF/UserModel/Extensions/TestXSSFCellFill.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFBugs.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFCellStyle.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFColor.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFFont.cs
  testcases/ooxml/XSSF/UserModel/TestXSSFSheet.cs
  testcases/test-data/spreadsheet/customIndexedColors.xlsx
Labels: bug, poi

#1555 Add XWPFTable.NumberOfColumns
  ooxml/XWPF/Usermodel/XWPFTable.cs
  testcases/ooxml/XWPF/UserModel/TestXWPFTable.cs
Labels: enhancement, docx

#1549 Remove unnecessary array allocations for Split etc
  Directory.Build.props
  main/POIFS/Crypt/DataSpaceMapUtils.cs
  main/POIFS/FileSystem/NPOIFSDocument.cs
  ooxml/XSSF/Extractor/XSSFExportToXml.cs
  ooxml/XSSF/UserModel/Helpers/XSSFRowColShifter.cs
  ooxml/XSSF/UserModel/Helpers/XSSFXmlColumnPr.cs
  ooxml/XSSF/UserModel/XSSFConditionalFormatting.cs
  ooxml/XSSF/UserModel/XSSFSheet.cs
  ooxml/XSSF/UserModel/XSSFTable.cs
  openxml4Net/OPC/PackagingUriHelper.cs
  testcases/main/App.config
  testcases/ooxml/App.config
  testcases/openxml4net/App.config
Labels: performance

#1559 Update some ToString functions
  OpenXmlFormats/Spreadsheet/Styles/CT_Border.cs
  OpenXmlFormats/Spreadsheet/Styles/CT_Colors.cs
  OpenXmlFormats/Spreadsheet/Styles/CT_Font.cs
  OpenXmlFormats/Spreadsheet/Styles/CT_Xf.cs
  ooxml/XSSF/UserModel/XSSFClientAnchor.cs
Labels: enhancement

#1563 Read label options only if label length > 0
  main/HSSF/Record/LabelRecord.cs
  testcases/main/HSSF/UserModel/TestHSSFWorkbook.cs
  testcases/test-data/spreadsheet/optional_label_options.xls
Labels: bug, xls
